/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminInviteRouteImport } from './routes/admin-invite'
import { Route as AssetsRouteImport } from './routes/assets'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BoardRouteImport } from './routes/board'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as EventsRouteImport } from './routes/events'
import { Route as FundraisingRouteImport } from './routes/fundraising'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as MembershipRouteImport } from './routes/membership'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as ReferRouteImport } from './routes/refer'
import { Route as SurveysRouteImport } from './routes/surveys'
import { Route as TypographyRouteImport } from './routes/typography'
import { Route as VillageGroupsRouteImport } from './routes/village-groups'
import { Route as VolunteerRouteImport } from './routes/volunteer'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as NewsIndexRouteImport } from './routes/news.index'
import { Route as NewsIdRouteImport } from './routes/news.$id'
import { Route as NewsUnsubscribeRouteImport } from './routes/news.unsubscribe'
import { Route as RsvpReportEventIdRouteImport } from './routes/rsvp-report.$eventId'
import { Route as RsvpTokenRouteImport } from './routes/rsvp.$token'
import { Route as ApiPublicHooksCampaignStatusRouteImport } from './routes/api/public/hooks/campaign-status'
import { Route as ApiPublicHooksDailyRsvpDigestRouteImport } from './routes/api/public/hooks/daily-rsvp-digest'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInviteRoute = AdminInviteRouteImport.update({
  id: '/admin-invite',
  path: '/admin-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsRoute = AssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardRoute = BoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const FundraisingRoute = FundraisingRouteImport.update({
  id: '/fundraising',
  path: '/fundraising',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipRoute = MembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferRoute = ReferRouteImport.update({
  id: '/refer',
  path: '/refer',
  getParentRoute: () => rootRouteImport,
} as any)
const SurveysRoute = SurveysRouteImport.update({
  id: '/surveys',
  path: '/surveys',
  getParentRoute: () => rootRouteImport,
} as any)
const TypographyRoute = TypographyRouteImport.update({
  id: '/typography',
  path: '/typography',
  getParentRoute: () => rootRouteImport,
} as any)
const VillageGroupsRoute = VillageGroupsRouteImport.update({
  id: '/village-groups',
  path: '/village-groups',
  getParentRoute: () => rootRouteImport,
} as any)
const VolunteerRoute = VolunteerRouteImport.update({
  id: '/volunteer',
  path: '/volunteer',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIdRoute = NewsIdRouteImport.update({
  id: '/news/$id',
  path: '/news/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsUnsubscribeRoute = NewsUnsubscribeRouteImport.update({
  id: '/news/unsubscribe',
  path: '/news/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const RsvpReportEventIdRoute = RsvpReportEventIdRouteImport.update({
  id: '/rsvp-report/$eventId',
  path: '/rsvp-report/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const RsvpTokenRoute = RsvpTokenRouteImport.update({
  id: '/rsvp/$token',
  path: '/rsvp/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksCampaignStatusRoute =
  ApiPublicHooksCampaignStatusRouteImport.update({
    id: '/api/public/hooks/campaign-status',
    path: '/api/public/hooks/campaign-status',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDailyRsvpDigestRoute =
  ApiPublicHooksDailyRsvpDigestRouteImport.update({
    id: '/api/public/hooks/daily-rsvp-digest',
    path: '/api/public/hooks/daily-rsvp-digest',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin-invite': typeof AdminInviteRoute
  '/assets': typeof AssetsRoute
  '/auth': typeof AuthRoute
  '/board': typeof BoardRoute
  '/contact': typeof ContactRoute
  '/documents': typeof DocumentsRoute
  '/donate': typeof DonateRoute
  '/events': typeof EventsRoute
  '/fundraising': typeof FundraisingRoute
  '/gallery': typeof GalleryRoute
  '/jobs': typeof JobsRoute
  '/membership': typeof MembershipRoute
  '/partners': typeof PartnersRoute
  '/refer': typeof ReferRoute
  '/surveys': typeof SurveysRoute
  '/typography': typeof TypographyRoute
  '/village-groups': typeof VillageGroupsRoute
  '/volunteer': typeof VolunteerRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/news/$id': typeof NewsIdRoute
  '/news/unsubscribe': typeof NewsUnsubscribeRoute
  '/rsvp-report/$eventId': typeof RsvpReportEventIdRoute
  '/rsvp/$token': typeof RsvpTokenRoute
  '/news/': typeof NewsIndexRoute
  '/api/public/hooks/campaign-status': typeof ApiPublicHooksCampaignStatusRoute
  '/api/public/hooks/daily-rsvp-digest': typeof ApiPublicHooksDailyRsvpDigestRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin-invite': typeof AdminInviteRoute
  '/assets': typeof AssetsRoute
  '/auth': typeof AuthRoute
  '/board': typeof BoardRoute
  '/contact': typeof ContactRoute
  '/documents': typeof DocumentsRoute
  '/donate': typeof DonateRoute
  '/events': typeof EventsRoute
  '/fundraising': typeof FundraisingRoute
  '/gallery': typeof GalleryRoute
  '/jobs': typeof JobsRoute
  '/membership': typeof MembershipRoute
  '/partners': typeof PartnersRoute
  '/refer': typeof ReferRoute
  '/surveys': typeof SurveysRoute
  '/typography': typeof TypographyRoute
  '/village-groups': typeof VillageGroupsRoute
  '/volunteer': typeof VolunteerRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/news/$id': typeof NewsIdRoute
  '/news/unsubscribe': typeof NewsUnsubscribeRoute
  '/rsvp-report/$eventId': typeof RsvpReportEventIdRoute
  '/rsvp/$token': typeof RsvpTokenRoute
  '/news': typeof NewsIndexRoute
  '/api/public/hooks/campaign-status': typeof ApiPublicHooksCampaignStatusRoute
  '/api/public/hooks/daily-rsvp-digest': typeof ApiPublicHooksDailyRsvpDigestRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/admin-invite': typeof AdminInviteRoute
  '/assets': typeof AssetsRoute
  '/auth': typeof AuthRoute
  '/board': typeof BoardRoute
  '/contact': typeof ContactRoute
  '/documents': typeof DocumentsRoute
  '/donate': typeof DonateRoute
  '/events': typeof EventsRoute
  '/fundraising': typeof FundraisingRoute
  '/gallery': typeof GalleryRoute
  '/jobs': typeof JobsRoute
  '/membership': typeof MembershipRoute
  '/partners': typeof PartnersRoute
  '/refer': typeof ReferRoute
  '/surveys': typeof SurveysRoute
  '/typography': typeof TypographyRoute
  '/village-groups': typeof VillageGroupsRoute
  '/volunteer': typeof VolunteerRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/news/$id': typeof NewsIdRoute
  '/news/unsubscribe': typeof NewsUnsubscribeRoute
  '/rsvp-report/$eventId': typeof RsvpReportEventIdRoute
  '/rsvp/$token': typeof RsvpTokenRoute
  '/news/': typeof NewsIndexRoute
  '/api/public/hooks/campaign-status': typeof ApiPublicHooksCampaignStatusRoute
  '/api/public/hooks/daily-rsvp-digest': typeof ApiPublicHooksDailyRsvpDigestRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin-invite'
    | '/assets'
    | '/auth'
    | '/board'
    | '/contact'
    | '/documents'
    | '/donate'
    | '/events'
    | '/fundraising'
    | '/gallery'
    | '/jobs'
    | '/membership'
    | '/partners'
    | '/refer'
    | '/surveys'
    | '/typography'
    | '/village-groups'
    | '/volunteer'
    | '/admin'
    | '/news/$id'
    | '/news/unsubscribe'
    | '/rsvp-report/$eventId'
    | '/rsvp/$token'
    | '/news/'
    | '/api/public/hooks/campaign-status'
    | '/api/public/hooks/daily-rsvp-digest'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin-invite'
    | '/assets'
    | '/auth'
    | '/board'
    | '/contact'
    | '/documents'
    | '/donate'
    | '/events'
    | '/fundraising'
    | '/gallery'
    | '/jobs'
    | '/membership'
    | '/partners'
    | '/refer'
    | '/surveys'
    | '/typography'
    | '/village-groups'
    | '/volunteer'
    | '/admin'
    | '/news/$id'
    | '/news/unsubscribe'
    | '/rsvp-report/$eventId'
    | '/rsvp/$token'
    | '/news'
    | '/api/public/hooks/campaign-status'
    | '/api/public/hooks/daily-rsvp-digest'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/admin-invite'
    | '/assets'
    | '/auth'
    | '/board'
    | '/contact'
    | '/documents'
    | '/donate'
    | '/events'
    | '/fundraising'
    | '/gallery'
    | '/jobs'
    | '/membership'
    | '/partners'
    | '/refer'
    | '/surveys'
    | '/typography'
    | '/village-groups'
    | '/volunteer'
    | '/_authenticated/admin'
    | '/news/$id'
    | '/news/unsubscribe'
    | '/rsvp-report/$eventId'
    | '/rsvp/$token'
    | '/news/'
    | '/api/public/hooks/campaign-status'
    | '/api/public/hooks/daily-rsvp-digest'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AdminInviteRoute: typeof AdminInviteRoute
  AssetsRoute: typeof AssetsRoute
  AuthRoute: typeof AuthRoute
  BoardRoute: typeof BoardRoute
  ContactRoute: typeof ContactRoute
  DocumentsRoute: typeof DocumentsRoute
  DonateRoute: typeof DonateRoute
  EventsRoute: typeof EventsRoute
  FundraisingRoute: typeof FundraisingRoute
  GalleryRoute: typeof GalleryRoute
  JobsRoute: typeof JobsRoute
  MembershipRoute: typeof MembershipRoute
  PartnersRoute: typeof PartnersRoute
  ReferRoute: typeof ReferRoute
  SurveysRoute: typeof SurveysRoute
  TypographyRoute: typeof TypographyRoute
  VillageGroupsRoute: typeof VillageGroupsRoute
  VolunteerRoute: typeof VolunteerRoute
  NewsIdRoute: typeof NewsIdRoute
  NewsUnsubscribeRoute: typeof NewsUnsubscribeRoute
  RsvpReportEventIdRoute: typeof RsvpReportEventIdRoute
  RsvpTokenRoute: typeof RsvpTokenRoute
  NewsIndexRoute: typeof NewsIndexRoute
  ApiPublicHooksCampaignStatusRoute: typeof ApiPublicHooksCampaignStatusRoute
  ApiPublicHooksDailyRsvpDigestRoute: typeof ApiPublicHooksDailyRsvpDigestRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-invite': {
      id: '/admin-invite'
      path: '/admin-invite'
      fullPath: '/admin-invite'
      preLoaderRoute: typeof AdminInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets': {
      id: '/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board': {
      id: '/board'
      path: '/board'
      fullPath: '/board'
      preLoaderRoute: typeof BoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fundraising': {
      id: '/fundraising'
      path: '/fundraising'
      fullPath: '/fundraising'
      preLoaderRoute: typeof FundraisingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership': {
      id: '/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof MembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refer': {
      id: '/refer'
      path: '/refer'
      fullPath: '/refer'
      preLoaderRoute: typeof ReferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/surveys': {
      id: '/surveys'
      path: '/surveys'
      fullPath: '/surveys'
      preLoaderRoute: typeof SurveysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/typography': {
      id: '/typography'
      path: '/typography'
      fullPath: '/typography'
      preLoaderRoute: typeof TypographyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/village-groups': {
      id: '/village-groups'
      path: '/village-groups'
      fullPath: '/village-groups'
      preLoaderRoute: typeof VillageGroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volunteer': {
      id: '/volunteer'
      path: '/volunteer'
      fullPath: '/volunteer'
      preLoaderRoute: typeof VolunteerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/news/': {
      id: '/news/'
      path: '/news'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$id': {
      id: '/news/$id'
      path: '/news/$id'
      fullPath: '/news/$id'
      preLoaderRoute: typeof NewsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/unsubscribe': {
      id: '/news/unsubscribe'
      path: '/news/unsubscribe'
      fullPath: '/news/unsubscribe'
      preLoaderRoute: typeof NewsUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rsvp-report/$eventId': {
      id: '/rsvp-report/$eventId'
      path: '/rsvp-report/$eventId'
      fullPath: '/rsvp-report/$eventId'
      preLoaderRoute: typeof RsvpReportEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rsvp/$token': {
      id: '/rsvp/$token'
      path: '/rsvp/$token'
      fullPath: '/rsvp/$token'
      preLoaderRoute: typeof RsvpTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/campaign-status': {
      id: '/api/public/hooks/campaign-status'
      path: '/api/public/hooks/campaign-status'
      fullPath: '/api/public/hooks/campaign-status'
      preLoaderRoute: typeof ApiPublicHooksCampaignStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/daily-rsvp-digest': {
      id: '/api/public/hooks/daily-rsvp-digest'
      path: '/api/public/hooks/daily-rsvp-digest'
      fullPath: '/api/public/hooks/daily-rsvp-digest'
      preLoaderRoute: typeof ApiPublicHooksDailyRsvpDigestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AdminInviteRoute: AdminInviteRoute,
  AssetsRoute: AssetsRoute,
  AuthRoute: AuthRoute,
  BoardRoute: BoardRoute,
  ContactRoute: ContactRoute,
  DocumentsRoute: DocumentsRoute,
  DonateRoute: DonateRoute,
  EventsRoute: EventsRoute,
  FundraisingRoute: FundraisingRoute,
  GalleryRoute: GalleryRoute,
  JobsRoute: JobsRoute,
  MembershipRoute: MembershipRoute,
  PartnersRoute: PartnersRoute,
  ReferRoute: ReferRoute,
  SurveysRoute: SurveysRoute,
  TypographyRoute: TypographyRoute,
  VillageGroupsRoute: VillageGroupsRoute,
  VolunteerRoute: VolunteerRoute,
  NewsIdRoute: NewsIdRoute,
  NewsUnsubscribeRoute: NewsUnsubscribeRoute,
  RsvpReportEventIdRoute: RsvpReportEventIdRoute,
  RsvpTokenRoute: RsvpTokenRoute,
  NewsIndexRoute: NewsIndexRoute,
  ApiPublicHooksCampaignStatusRoute: ApiPublicHooksCampaignStatusRoute,
  ApiPublicHooksDailyRsvpDigestRoute: ApiPublicHooksDailyRsvpDigestRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
