/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AssetsRouteImport } from './routes/assets'
import { Route as BoardRouteImport } from './routes/board'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as EventsRouteImport } from './routes/events'
import { Route as FundraisingRouteImport } from './routes/fundraising'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as MembershipRouteImport } from './routes/membership'
import { Route as PartnersRouteImport } from './routes/partners'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsRoute = AssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardRoute = BoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const FundraisingRoute = FundraisingRouteImport.update({
  id: '/fundraising',
  path: '/fundraising',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipRoute = MembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/assets': typeof AssetsRoute
  '/board': typeof BoardRoute
  '/contact': typeof ContactRoute
  '/documents': typeof DocumentsRoute
  '/donate': typeof DonateRoute
  '/events': typeof EventsRoute
  '/fundraising': typeof FundraisingRoute
  '/gallery': typeof GalleryRoute
  '/membership': typeof MembershipRoute
  '/partners': typeof PartnersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/assets': typeof AssetsRoute
  '/board': typeof BoardRoute
  '/contact': typeof ContactRoute
  '/documents': typeof DocumentsRoute
  '/donate': typeof DonateRoute
  '/events': typeof EventsRoute
  '/fundraising': typeof FundraisingRoute
  '/gallery': typeof GalleryRoute
  '/membership': typeof MembershipRoute
  '/partners': typeof PartnersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/assets': typeof AssetsRoute
  '/board': typeof BoardRoute
  '/contact': typeof ContactRoute
  '/documents': typeof DocumentsRoute
  '/donate': typeof DonateRoute
  '/events': typeof EventsRoute
  '/fundraising': typeof FundraisingRoute
  '/gallery': typeof GalleryRoute
  '/membership': typeof MembershipRoute
  '/partners': typeof PartnersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/assets'
    | '/board'
    | '/contact'
    | '/documents'
    | '/donate'
    | '/events'
    | '/fundraising'
    | '/gallery'
    | '/membership'
    | '/partners'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/assets'
    | '/board'
    | '/contact'
    | '/documents'
    | '/donate'
    | '/events'
    | '/fundraising'
    | '/gallery'
    | '/membership'
    | '/partners'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/assets'
    | '/board'
    | '/contact'
    | '/documents'
    | '/donate'
    | '/events'
    | '/fundraising'
    | '/gallery'
    | '/membership'
    | '/partners'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AssetsRoute: typeof AssetsRoute
  BoardRoute: typeof BoardRoute
  ContactRoute: typeof ContactRoute
  DocumentsRoute: typeof DocumentsRoute
  DonateRoute: typeof DonateRoute
  EventsRoute: typeof EventsRoute
  FundraisingRoute: typeof FundraisingRoute
  GalleryRoute: typeof GalleryRoute
  MembershipRoute: typeof MembershipRoute
  PartnersRoute: typeof PartnersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets': {
      id: '/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board': {
      id: '/board'
      path: '/board'
      fullPath: '/board'
      preLoaderRoute: typeof BoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fundraising': {
      id: '/fundraising'
      path: '/fundraising'
      fullPath: '/fundraising'
      preLoaderRoute: typeof FundraisingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership': {
      id: '/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof MembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AssetsRoute: AssetsRoute,
  BoardRoute: BoardRoute,
  ContactRoute: ContactRoute,
  DocumentsRoute: DocumentsRoute,
  DonateRoute: DonateRoute,
  EventsRoute: EventsRoute,
  FundraisingRoute: FundraisingRoute,
  GalleryRoute: GalleryRoute,
  MembershipRoute: MembershipRoute,
  PartnersRoute: PartnersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
